ifndef::env-github[:icons: font]
:toc: preamble
:toclevels: 2
:sectanchors:

ifdef::env-github[]
++++
<a id="readme-top"></a>
<div align="center">
<a href="https://github.com/dev-centr/business-bootstrap/graphs/contributors"><img src="https://img.shields.io/github/contributors/dev-centr/business-bootstrap.svg?style=for-the-badge" alt="Contributors"></a>
<a href="https://github.com/dev-centr/business-bootstrap/network/members"><img src="https://img.shields.io/github/forks/dev-centr/business-bootstrap.svg?style=for-the-badge" alt="Forks"></a>
<a href="https://github.com/dev-centr/business-bootstrap/stargazers"><img src="https://img.shields.io/github/stars/dev-centr/business-bootstrap.svg?style=for-the-badge" alt="Stars"></a>
<a href="https://github.com/dev-centr/business-bootstrap/issues"><img src="https://img.shields.io/github/issues/dev-centr/business-bootstrap.svg?style=for-the-badge" alt="Issues"></a>
<br />
<h3 align="center">Business Bootstrap</h3>
<p align="center">
Business bootstrap docs: email matrix, DMARC, org infra pattern.<br /><a href="https://docs.devcentr.org"><strong>Explore the docs ·</strong></a><br /><br />
<a href="https://github.com/dev-centr/business-bootstrap/issues">Report Bug</a>
&middot;
<a href="https://github.com/dev-centr/business-bootstrap/issues">Request Feature</a>
</p>
</div>
++++
endif::[]

ifndef::env-github[]
image:https://img.shields.io/github/contributors/dev-centr/business-bootstrap.svg?style=for-the-badge[Contributors,link=https://github.com/dev-centr/business-bootstrap/graphs/contributors]
image:https://img.shields.io/github/forks/dev-centr/business-bootstrap.svg?style=for-the-badge[Forks,link=https://github.com/dev-centr/business-bootstrap/network/members]
image:https://img.shields.io/github/stars/dev-centr/business-bootstrap.svg?style=for-the-badge[Stars,link=https://github.com/dev-centr/business-bootstrap/stargazers]
image:https://img.shields.io/github/issues/dev-centr/business-bootstrap.svg?style=for-the-badge[Issues,link=https://github.com/dev-centr/business-bootstrap/issues]

= Business Bootstrap

Business bootstrap docs: email matrix, DMARC, org infra pattern.

link:https://docs.devcentr.org[Explore the docs] ·
link:https://github.com/dev-centr/business-bootstrap/issues[Report Bug] ·
link:https://github.com/dev-centr/business-bootstrap/issues[Request Feature]
endif::[]

== About The Project

Product-agnostic guidance for bootstrapping tech-company support systems: email (human vs product), DMARC, org-level IaC (`infra` repos), and light ITIL-shaped service catalog naming.

Organized with Diátaxis (tutorials, how-to, reference, explanation). Aggregated on link:https://docs.devcentr.org[docs.devcentr.org].

link:#readme-top[back to top]

== Changelog

See link:docs/modules/ROOT/pages/changelog.adoc[changelog.adoc].

== Contact

DevCentr.org — support@devcentr.org

* Project: https://github.com/dev-centr/business-bootstrap
* Site: https://docs.devcentr.org

link:#readme-top[back to top]
